/* Isolated, local-only browser fixture. Served only by preview-server.cjs. */
var PREVIEW_KEY='product-tool-qa-v1';
var previewSettings;
var supabaseClient=(function(){
  function initial(){return {product_lists:[{id:'00000000-0000-4000-8000-000000000001',title:'검증용 상품 리스트',author:'기능 검증',work_date:'2026-09-07',created_at:'2026-09-07T01:00:00Z',updated_at:'2026-09-07T01:00:00Z'}],product_items:[{id:'00000000-0000-4000-8000-000000000002',list_id:'00000000-0000-4000-8000-000000000001',seq:1,brand:'AVMATRIX',name_own:'검증용 HDMI 분배기',model:'SD1242-4K',need_retail:'필요',need_wholesale:'필요',need_naver:'불필요',price_retail:10000,price_wholesale:9000,price_wholesale_master:8000,image_url:'',done:false,automation:{}}],app_settings:[{key:'hidden_columns',value:[],updated_at:'2026-09-07T00:00:00Z'},{key:'product_automation_v1',value:previewSettings,updated_at:'2026-09-07T00:00:00Z'}]};}
  function db(){var existing=localStorage.getItem(PREVIEW_KEY);return existing?JSON.parse(existing):initial();}
  function write(d){localStorage.setItem(PREVIEW_KEY,JSON.stringify(d));}
  function from(table){var action='select',payload,filters=[],single=false;var q={select(){return q;},order(){return q;},eq(k,v){filters.push(r=>r[k]===v);return q;},in(k,v){filters.push(r=>v.includes(r[k]));return q;},single(){single=true;return q;},maybeSingle(){single=true;return q;},insert(v){action='insert';payload=v;return q;},update(v){action='update';payload=v;return q;},upsert(v){action='upsert';payload=v;return q;},delete(){action='delete';return q;},then(resolve,reject){try{var d=db(),rows=d[table],out=rows.filter(r=>filters.every(f=>f(r)));if(action==='insert'){out=[Object.assign({id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()},payload)];rows.push(...out);}if(action==='update')out.forEach(r=>Object.assign(r,payload));if(action==='delete'){d[table]=rows.filter(r=>!out.includes(r));if(table==='product_lists')d.product_items=d.product_items.filter(i=>!out.some(l=>l.id===i.list_id));}if(action==='upsert'){out=Array.isArray(payload)?payload:[payload];out.forEach(r=>{var old=rows.find(x=>r.id?x.id===r.id:x.key===r.key);if(old)Object.assign(old,r);else rows.push(r);});}if(action!=='select')write(d);return Promise.resolve({data:single?out[0]||null:out,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return q;}
  return {from,async rpc(name,args){var d=db(),l=d.product_lists.find(l=>l.id===args.p_list.id);if(!l)return {error:{message:'List not found'}};Object.assign(l,args.p_list,{updated_at:new Date().toISOString()});d.product_items=d.product_items.filter(i=>!args.p_removed_ids.includes(i.id));args.p_items.forEach(i=>{var old=d.product_items.find(x=>x.id===i.id);if(old)Object.assign(old,i);else d.product_items.push({...i,done:false});});write(d);return {error:null,data:null};},channel(){return {on(){return this;},subscribe(cb){cb('SUBSCRIBED');return this;}};},storage:{from(){return {async upload(path,file){var data=await new Promise(resolve=>{var r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file);});var result=await fetch('/__qa/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path,data})});return result.ok?{error:null}:{error:{message:'upload failed'}};},getPublicUrl(path){return {data:{publicUrl:location.origin+'/__qa/files/'+path}};}};}}};
})();
document.addEventListener('DOMContentLoaded',()=>{var badge=document.createElement('div');badge.textContent='검증용 미리보기 · 운영 DB 미연결';badge.style.cssText='position:fixed;bottom:8px;left:8px;z-index:99999;background:#fff2cf;border:1px solid #cba;padding:6px 12px;border-radius:99px;font-size:11px;pointer-events:none';document.body.appendChild(badge);});
